name: vercel upload (kwd)
on : push
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs : 
 build:
  runs-on : unbutu-latest
  steps: 
   - uses : action/checkout@v2
   - uses : action/setup-node@v1
     with :
       node-version : 18
   - run : npm ci
   - run: npm install --global vercel@latest
   - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
   - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
   - run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  
